# Gradient Calculation in PyTorch with Autograd

In [15]:
import torch

In [16]:
x = torch.randn(3, requires_grad=True)
print(x)

tensor([-1.9406,  0.4365, -0.1932], requires_grad=True)


In [17]:
y = x + 2
print(y)

tensor([0.0594, 2.4365, 1.8068], grad_fn=<AddBackward0>)


In [18]:
z = y * y * 2
print(z)

tensor([7.0663e-03, 1.1873e+01, 6.5292e+00], grad_fn=<MulBackward0>)


In [19]:
z = z.mean()
print(z)

tensor(6.1363, grad_fn=<MeanBackward0>)


Note: `tensor.backward()` is calculated based on the Jacobian matrix of the output with respect to the input. The Jacobian matrix is a matrix of all first-order partial derivatives of the output with respect to the input. For example, if the output is a scalar value, the Jacobian matrix is a vector of first-order partial derivatives of the output with respect to the input. If the output is a vector, the Jacobian matrix is a matrix of first-order partial derivatives of the output with respect to the input.

In [20]:
z.backward()                    # dz/dx
# z.backward(torch.tensor(1.))  # dz/dx
print(x.grad)

tensor([0.0793, 3.2486, 2.4091])


## Prevent Gradient Calculation

In [23]:
# Prevent tracking history

# x.requires_grad_(False)
print(x.requires_grad_(False))
# x.detach()
print(y.detach())
# with torch.no_grad():
with torch.no_grad():
    print(x + 2)

tensor([-1.9406,  0.4365, -0.1932])
tensor([0.0594, 2.4365, 1.8068])
tensor([0.0594, 2.4365, 1.8068])


## `tensor.grad` accumulates gradients

In [26]:
# Dummy example
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
    model_output = (weights * 3).sum()
    model_output.backward()
    print(weights.grad)

    weights.grad.zero_()                        # Manually zero the gradients after updating weights

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
