# Tensor Basics

In [41]:
import torch

## Tensor Initialization

In [42]:
# Empty tensor
x = torch.empty(5, 3)
print(x)
print(x.dtype)
print(x.size())

tensor([[9.3674e-39, 1.0745e-38, 1.0653e-38],
        [9.5510e-39, 1.0561e-38, 1.0194e-38],
        [1.1112e-38, 1.0561e-38, 9.9184e-39],
        [1.0653e-38, 4.1327e-39, 1.0194e-38],
        [1.0469e-38, 8.9082e-39, 1.5134e-43]])
torch.float32
torch.Size([5, 3])


In [43]:
# Random tensor
x = torch.rand(5, 3)
print(x)
print(x.dtype)
print(x.size())

tensor([[0.0887, 0.2164, 0.6078],
        [0.6059, 0.7854, 0.9099],
        [0.1518, 0.4695, 0.5882],
        [0.4456, 0.0313, 0.4858],
        [0.4134, 0.2083, 0.6035]])
torch.float32
torch.Size([5, 3])


In [44]:
# Zero tensor
x = torch.zeros(5, 3, dtype=torch.long)
print(x)
print(x.dtype)
print(x.size())

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
torch.int64
torch.Size([5, 3])


In [45]:
# One tensor
x = torch.ones(5, 3, dtype=torch.long)
print(x)
print(x.dtype)
print(x.size())

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])
torch.int64
torch.Size([5, 3])


In [46]:
# Tensor from data
x = torch.tensor([5.5, 3])
print(x)
print(x.dtype)
print(x.size())

tensor([5.5000, 3.0000])
torch.float32
torch.Size([2])


In [47]:
# Gradient Calculation
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


## Tensor Operations

In [48]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)

print(x)
print(y)

tensor([[0.0223, 0.0260],
        [0.0547, 0.0035]])
tensor([[0.7440, 0.8342],
        [0.4033, 0.5074]])


In [49]:
# Addition with + operator
z = x + y
print(z)

# Addition with torch.add()
z = torch.add(x, y)
print(z)

# In place addition
y.add_(x)                       # y = y + x
print(y)

tensor([[0.7663, 0.8602],
        [0.4580, 0.5109]])
tensor([[0.7663, 0.8602],
        [0.4580, 0.5109]])
tensor([[0.7663, 0.8602],
        [0.4580, 0.5109]])


In [50]:
# Subtraction with - operator
z = x - y
print(z)

# Subtraction with torch.sub()
z = torch.sub(x, y)
print(z)

# In place subtraction
y.sub_(x)                       # y = y - x
print(y)

tensor([[-0.7440, -0.8342],
        [-0.4033, -0.5074]])
tensor([[-0.7440, -0.8342],
        [-0.4033, -0.5074]])
tensor([[0.7440, 0.8342],
        [0.4033, 0.5074]])


In [51]:
# Multiplication with * operator
z = x * y
print(z)

# Multiplication with torch.mul()
z = torch.mul(x, y)
print(z)

# In place multiplication
y.mul_(x)                       # y = y * x
print(y)

tensor([[0.0166, 0.0217],
        [0.0221, 0.0018]])
tensor([[0.0166, 0.0217],
        [0.0221, 0.0018]])
tensor([[0.0166, 0.0217],
        [0.0221, 0.0018]])


In [52]:
# Division with / operator
z = x / y
print(z)

# Division with torch.div()
z = torch.div(x, y)
print(z)

# In place division
y.div_(x)                       # y = y / x
print(y)

tensor([[1.3442, 1.1987],
        [2.4794, 1.9710]])
tensor([[1.3442, 1.1987],
        [2.4794, 1.9710]])
tensor([[0.7440, 0.8342],
        [0.4033, 0.5074]])


In [53]:
# Slicing
x = torch.rand(5, 3)
print(x)

print(x[:, 1])                  # Second column
print(x[1, :])                  # Second row
print(x[1, 1].item())           # Second row, second column as a scalar (Works only for one element tensors)

tensor([[0.4691, 0.0980, 0.2262],
        [0.9690, 0.1789, 0.4162],
        [0.4478, 0.6596, 0.2144],
        [0.9134, 0.2097, 0.4753],
        [0.2667, 0.9127, 0.2867]])
tensor([0.0980, 0.1789, 0.6596, 0.2097, 0.9127])
tensor([0.9690, 0.1789, 0.4162])
0.17894965410232544


In [54]:
# Resizing
x = torch.rand(4, 4)
print(x)

y = x.view(16)
print(y)
print(y.size())

y = x.view(-1, 8)               # The size -1 is inferred from other dimensions
print(y)
print(y.size())

tensor([[0.9311, 0.1564, 0.1228, 0.2647],
        [0.8236, 0.4388, 0.2305, 0.5029],
        [0.7511, 0.6201, 0.8383, 0.1813],
        [0.9613, 0.5270, 0.7812, 0.3567]])
tensor([0.9311, 0.1564, 0.1228, 0.2647, 0.8236, 0.4388, 0.2305, 0.5029, 0.7511,
        0.6201, 0.8383, 0.1813, 0.9613, 0.5270, 0.7812, 0.3567])
torch.Size([16])
tensor([[0.9311, 0.1564, 0.1228, 0.2647, 0.8236, 0.4388, 0.2305, 0.5029],
        [0.7511, 0.6201, 0.8383, 0.1813, 0.9613, 0.5270, 0.7812, 0.3567]])
torch.Size([2, 8])


## Tensor and Numpy

In [55]:
import numpy as np

Note that the tensor and numpy array will share their underlying memory locations (if the numpy array is on CPU), and changing one will change the other.

In [56]:
a = torch.ones(5)
print(a, a.dtype)

b = a.numpy()
print(b, b.dtype)

tensor([1., 1., 1., 1., 1.]) torch.float32
[1. 1. 1. 1. 1.] float32


In [57]:
a = np.ones(5, dtype=np.int32)
print(a, a.dtype)

b = torch.from_numpy(a)         
print(b, b.dtype)

[1 1 1 1 1] int32
tensor([1, 1, 1, 1, 1], dtype=torch.int32) torch.int32


## Tensor on GPU

In [58]:
if torch.cuda.is_available():
    device = torch.device("cuda")           # a CUDA device object
    y = torch.ones(5, device=device)        # directly create a tensor on GPU
    x = torch.ones(5)
    x = x.to(device)                        # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))        # ``.to`` can also change dtype together!